Get to know the data

- How many rows and columns does each file have? What does one row represent?
- Which columns are numbers, which are text and which are dates?
- Write down one question each file could help you answer

In [0]:
import pandas as pd
import numpy as np

In [0]:
product = spark.table("python.default.1790098701587_products").toPandas()

display(product)

ProductID,ProductName,Category,UnitPrice
2001,Wireless Mouse,Electronics,18.0
2002,Mechanical Keyboard,Electronics,62.0
2003,USB-C Cable,Accessories,9.0
2004,Power Bank,Electronics,35.0
2005,Laptop Stand,Accessories,28.0
2006,Webcam,Electronics,48.0
2007,Headphones,Electronics,75.0
2008,Phone Case,Accessories,14.0
2009,Smart Watch,Wearables,120.0
2010,Fitness Band,Wearables,55.0
2011,Desk Lamp,Home Office,32.0
2012,Office Chair,Home Office,180.0
2013,Notebook,Stationery,7.0
2014,Backpack,Accessories,42.0
2015,Bluetooth Speaker,Electronics,58.0
2016,Monitor,Electronics,21.0
2017,HDMI Cable,Accessories,11.0
2018,Microphone,Electronics,85.0
2019,Tablet,Electronics,260.0
2020,Gaming Controller,Gaming,68.0

Clean the data

- Missing values: which columns have blanks? Should you remove, fill or keep those rows?
- Duplicates: are any orders recorded more than once?
- Values that make no sense: look at the smallest and largest numbers in each numeric column. Do the product prices look sensible for each item?
- Inconsistent text: are the same cities spelled in more than one way?
- Broken links: does every order point to a customer and product that actually exist?

In [0]:
product.shape

(20, 4)

In [0]:
product.columns

Index(['ProductID', 'ProductName', 'Category', 'UnitPrice'], dtype='object')

In [0]:
product.dtypes

ProductID        int64
ProductName     object
Category        object
UnitPrice      float64
dtype: object

In [0]:
product.head()

   ProductID          ProductName     Category  UnitPrice
0       2001       Wireless Mouse  Electronics       18.0
1       2002  Mechanical Keyboard  Electronics       62.0
2       2003          USB-C Cable  Accessories        9.0
3       2004           Power Bank  Electronics       35.0
4       2005         Laptop Stand  Accessories       28.0

In [0]:
# duplicated() checks if the same row appears more than once.
# sum() counts the number of duplicate rows.
print(product.duplicated().sum())
print(product["ProductID"].duplicated().sum())

0
0

In [0]:
# isnull() checks every cell and asks:
# "Is this cell empty/missing?"
# sum() then counts how many missing values there are in each column.
# So the result tells us how many blanks
# each column contains.

product.isnull().sum()

ProductID      0
ProductName    0
Category       0
UnitPrice      0
dtype: int64

In [0]:
# Check the numerical columns in the products table.
# The most important number here is UnitPrice.
# We want to see the cheapest and most expensive
# products and check whether those prices make sense.

product.describe()

        ProductID   UnitPrice
count    20.00000   20.000000
mean   2010.50000   61.400000
std       5.91608   62.836798
min    2001.00000    7.000000
25%    2005.75000   20.250000
50%    2010.50000   45.000000
75%    2015.25000   69.750000
max    2020.00000  260.000000

In [0]:
# describe() gives us statistics about UnitPrice.
# We are mainly interested in the minimum and maximum price.
# This helps us identify prices that may not make sense,

print(product["UnitPrice"].describe())

count     20.000000
mean      61.400000
std       62.836798
min        7.000000
25%       20.250000
50%       45.000000
75%       69.750000
max      260.000000
Name: UnitPrice, dtype: float64

In [0]:
# Sort the products from cheapest to most expensive.
# ascending=True means:
# smallest price → largest price

product.sort_values('UnitPrice', ascending=True)

    ProductID          ProductName     Category  UnitPrice
12       2013             Notebook   Stationery        7.0
2        2003          USB-C Cable  Accessories        9.0
16       2017           HDMI Cable  Accessories       11.0
7        2008           Phone Case  Accessories       14.0
0        2001       Wireless Mouse  Electronics       18.0
15       2016              Monitor  Electronics       21.0
4        2005         Laptop Stand  Accessories       28.0
10       2011            Desk Lamp  Home Office       32.0
3        2004           Power Bank  Electronics       35.0
13       2014             Backpack  Accessories       42.0
5        2006               Webcam  Electronics       48.0
9        2010         Fitness Band    Wearables       55.0
14       2015    Bluetooth Speaker  Electronics       58.0
1        2002  Mechanical Keyboard  Electronics       62.0
19       2020    Gaming Controller       Gaming       68.0
6        2007           Headphones  Electronics       75.0
17       2018           Microphone  Electronics       85.0
8        2009          Smart Watch    Wearables      120.0
11       2012         Office Chair  Home Office      180.0
18       2019               Tablet  Electronics      260.0

In [0]:
 # Sort the products from most expensive to cheapest.
# ascending=False means:
# largest price → smallest price

product.sort_values('UnitPrice', ascending=False)

    ProductID          ProductName     Category  UnitPrice
18       2019               Tablet  Electronics      260.0
11       2012         Office Chair  Home Office      180.0
8        2009          Smart Watch    Wearables      120.0
17       2018           Microphone  Electronics       85.0
6        2007           Headphones  Electronics       75.0
19       2020    Gaming Controller       Gaming       68.0
1        2002  Mechanical Keyboard  Electronics       62.0
14       2015    Bluetooth Speaker  Electronics       58.0
9        2010         Fitness Band    Wearables       55.0
5        2006               Webcam  Electronics       48.0
13       2014             Backpack  Accessories       42.0
3        2004           Power Bank  Electronics       35.0
10       2011            Desk Lamp  Home Office       32.0
4        2005         Laptop Stand  Accessories       28.0
15       2016              Monitor  Electronics       21.0
0        2001       Wireless Mouse  Electronics       18.0
7        2008           Phone Case  Accessories       14.0
16       2017           HDMI Cable  Accessories       11.0
2        2003          USB-C Cable  Accessories        9.0
12       2013             Notebook   Stationery        7.0

In [0]:
 #Shows the distinct values in the ProductName column
 #This helps us to see different peoduct we have in our dataset.
product["ProductName"].unique()

array(['Wireless Mouse', 'Mechanical Keyboard', 'USB-C Cable',
       'Power Bank', 'Laptop Stand', 'Webcam', 'Headphones', 'Phone Case',
       'Smart Watch', 'Fitness Band', 'Desk Lamp', 'Office Chair',
       'Notebook', 'Backpack', 'Bluetooth Speaker', 'Monitor',
       'HDMI Cable', 'Microphone', 'Tablet', 'Gaming Controller'],
      dtype=object)

In [0]:
product["ProductName"].value_counts()

ProductName
Wireless Mouse         1
Mechanical Keyboard    1
Tablet                 1
Microphone             1
HDMI Cable             1
Monitor                1
Bluetooth Speaker      1
Backpack               1
Notebook               1
Office Chair           1
Desk Lamp              1
Fitness Band           1
Smart Watch            1
Phone Case             1
Headphones             1
Webcam                 1
Laptop Stand           1
Power Bank             1
USB-C Cable            1
Gaming Controller      1
Name: count, dtype: int64

In [0]:
product["Category"].value_counts()

Category
Electronics    9
Accessories    5
Wearables      2
Home Office    2
Stationery     1
Gaming         1
Name: count, dtype: int64

In [0]:
print(product["UnitPrice"].min())
print(product["UnitPrice"].max())
print(product["UnitPrice"].mean())
print(product["UnitPrice"].median())

7.0
260.0
61.4
45.0

In [0]:
# strip() removes unnecessary spaces before and after text.
product["ProductName"] = product["ProductName"].str.strip()
product["Category"] = product["Category"].str.strip()

print(product["Category"].unique())

['Electronics' 'Accessories' 'Wearables' 'Home Office' 'Stationery'
 'Gaming']

In [0]:
 # Find products with zero or negative prices
zero_or_negative = product[product["UnitPrice"] <= 0]
if len(zero_or_negative) == 0:
    print("No products with zero or negative prices found.")
else:
    display(zero_or_negative)

No products with zero or negative prices found.

In [0]:
display(product)

ProductID,ProductName,Category,UnitPrice
2001,Wireless Mouse,Electronics,18.0
2002,Mechanical Keyboard,Electronics,62.0
2003,USB-C Cable,Accessories,9.0
2004,Power Bank,Electronics,35.0
2005,Laptop Stand,Accessories,28.0
2006,Webcam,Electronics,48.0
2007,Headphones,Electronics,75.0
2008,Phone Case,Accessories,14.0
2009,Smart Watch,Wearables,120.0
2010,Fitness Band,Wearables,55.0
2011,Desk Lamp,Home Office,32.0
2012,Office Chair,Home Office,180.0
2013,Notebook,Stationery,7.0
2014,Backpack,Accessories,42.0
2015,Bluetooth Speaker,Electronics,58.0
2016,Monitor,Electronics,21.0
2017,HDMI Cable,Accessories,11.0
2018,Microphone,Electronics,85.0
2019,Tablet,Electronics,260.0
2020,Gaming Controller,Gaming,68.0